module.exports = [ {
    title: "禁令标志",
    list: [ {
        title: "禁止通行",
        image: "1001.gif",
        desc: "表示禁止一切车辆和行人通行。此标志设在禁止通行的道路入口处。"
    }, {
        title: "禁止三轮车机动车通行",
        image: "1002.gif",
        desc: "表示禁止三轮机动车通行。此标志设在禁止三轮机动车通行的路段入口处。"
    }, {
        title: "禁止拖拉机通行",
        image: "1003.gif",
        desc: "表示禁止拖拉机通行。此标志设在禁止拖拉机通行的路段入口处。"
    }, {
        title: "禁止非机动车通行",
        image: "1004.gif",
        desc: "表示禁止非机动车通行。此标志设在禁止非机动车通行的路段入口处。"
    }, {
        title: "禁止驶入",
        image: "1005.gif",
        desc: "表示禁止车辆驶入。此标志设在禁止驶入的路段入口处。"
    }, {
        title: "禁止大型客车通行",
        image: "1006.gif",
        desc: "表示禁止大型客车通行。此标志设在禁止大型客车通行的路段入口处。"
    }, {
        title: "禁止农用车通行",
        image: "1007.gif",
        desc: "表示禁止农用运输车通行。此标志设在禁止农用运输车通行的路段入口处。"
    }, {
        title: "禁止畜力车通行",
        image: "1008.gif",
        desc: "表示禁止畜力车通行。此标志设在禁止畜力车通行的路段入口处。"
    }, {
        title: "禁止机动车通行",
        image: "1009.gif",
        desc: "表示禁止某种机动车通行。此标志设在禁止机动车通行的路段入口处。"
    }, {
        title: "禁止小型客车通行",
        image: "1010.gif",
        desc: "表示禁止小型客车通行。此标志设在禁止小型客车通行的路段入口处。"
    }, {
        title: "禁止二轮摩托车通行",
        image: "1011.gif",
        desc: "表示禁止两轮摩托车通行。此标志设在禁止两轮摩托车通行的路段入口处。"
    }, {
        title: "禁止人力货运三轮车通行",
        image: "1012.gif",
        desc: "表示禁止人力货运三轮车通行。此标志设在禁止人力货运三轮车通行的路段入口处。"
    }, {
        title: "禁止载货汽车通行",
        image: "1013.gif",
        desc: "表示禁止载货机动车通行。此标志设在载货机动车通行的路段入口处。"
    }, {
        title: "禁止汽车拖、挂车通行",
        image: "1014.gif",
        desc: "表示禁止汽车拖、挂车通行。此标志设在禁止汽车拖、挂车通行的路段入口处。"
    }, {
        title: "禁止某两种车通行",
        image: "1015.gif",
        desc: "表示禁止某两种车通行。此标志设在禁止某两种车通行的路段入口处。"
    }, {
        title: "禁止人力客运三轮车通行",
        image: "1016.gif",
        desc: "表示禁止人力客运三轮车通行。此标志设在禁止人力客运三轮车通行的路段入口处。"
    }, {
        title: "禁止人力车通行",
        image: "1017.gif",
        desc: "表示禁止人力车通行。此标志设在禁止人力车通行的路段入口处。"
    }, {
        title: "禁止向左转弯",
        image: "1018.gif",
        desc: "表示前方路口禁止一切车辆向左转弯。此标志设在禁止向左转弯的路口前适当位置"
    }, {
        title: "禁止直行和向左转弯",
        image: "1019.gif",
        desc: "表示前方路口禁止一切车辆直行和向左转弯。此标志设在禁止直行和向左转弯的路口前适当位置。"
    }, {
        title: "解除禁止超车",
        image: "1020.gif",
        desc: "表示禁止超车路段结束。此标志设在禁止超车的终点。"
    }, {
        title: "禁止骑自行车下坡",
        image: "1021.gif",
        desc: "表示禁止骑自行车下坡通行。此标志设在禁止骑自行车下坡通行的路段入口处。"
    }, {
        title: "禁止向右转弯",
        image: "1022.gif",
        desc: "表示前方路口禁止一切车辆向右转弯。此标志设在禁止向右转弯的路口前适当位置。"
    }, {
        title: "禁止直行和向右转弯",
        image: "1023.gif",
        desc: "表示前方路口禁止一切车辆直行和向右转弯。此标志设在禁止直行和向右转弯的路口前适当位置。"
    }, {
        title: "禁止车辆临时或长时停放",
        image: "1024.gif",
        desc: "表示在限定的范围内，禁止一切车辆临时或长时停放。此标志设在禁止车辆停放的地方。禁止车辆停放的时间、车种和范围可用辅助标志说明。"
    }, {
        title: "禁止骑自行车上坡",
        image: "1025.gif",
        desc: "表示禁止骑自行车上坡通行。此标志设在禁止骑自行车上坡通行的路段入口处。"
    }, {
        title: "禁止直行",
        image: "1026.gif",
        desc: "表示前方路口禁止一切车辆直行。此标志设在禁止直行的路口前适当位置。"
    }, {
        title: "禁止掉头",
        image: "1027.gif",
        desc: "表示前方路口禁止一切车辆掉头。此标志设在禁止掉头的路口前适当位置。"
    }, {
        title: "禁止车辆长时停放",
        image: "1028.gif",
        desc: "禁止车辆长时停放，临时停放不受限制。禁止车辆停放的时间、车种和范围可用辅助标志说明。"
    }, {
        title: "禁止行人通行",
        image: "1029.gif",
        desc: "表示禁止行人通行。此标志设在禁止行人通行的路段入口处。"
    }, {
        title: "禁止向左向右转弯",
        image: "1030.gif",
        desc: "表示前方路口禁止一切车辆向左向右转弯。此标志设在禁止向左向右转弯的路口前适当位置。"
    }, {
        title: "禁止超车",
        image: "1031.gif",
        desc: "表示该标志至前方解除禁止超车标志的路段内，不准机动车超车。此标志设在禁止超车的起点。"
    }, {
        title: "禁止鸣喇叭",
        image: "1032.gif",
        desc: "表示禁止鸣喇叭。此标志设在需要禁止鸣喇叭的地方。禁止鸣喇叭的时间和范围可用辅助标志说明。"
    }, {
        title: "限制宽度",
        image: "1033.gif",
        desc: "表示禁止装载宽度超过标志所示数值的车辆通行。此标志设在最大允许宽度受限制的地方。 以图为例：装载宽度不得超过3米"
    }, {
        title: "限制速度",
        image: "1034.gif",
        desc: "表示该标志至前方限制速度标志的路段内，机动车行驶速度不得超过标志所示数值。此标志设在需要限制车辆速度的路段的起点。以图为例：限制行驶时速不得超过40公里。"
    }, {
        title: "减速让行",
        image: "1035.gif",
        desc: "表示车辆应减速让行，告示车辆驾驶员必须慢行或停车，观察干路行车情况，在确保干道车辆优先的前提下，认为安全时方可续行。此标志设在视线良好交叉道路的次要路口。"
    }, {
        title: "限制高度",
        image: "1036.gif",
        desc: "表示禁止装载高度超过标志所示数值的车辆通行。此标志设在最大允许高度受限制的地方。 以图为例：装载高度不得超过3.5米。"
    }, {
        title: "解除限制速度",
        image: "1037.gif",
        desc: "表示限制速度路段结束。此标志设在限制车辆速度路段的重点。"
    }, {
        title: "会车让行",
        image: "1038.gif",
        desc: "表示车辆会车时，必须停车让对方车先行。设置在会车有困难的狭窄路段的一端或由于某种原因只能开放一条车道作双向通行路段的一端。"
    }, {
        title: "限制质量",
        image: "1039.gif",
        desc: "表示禁止总质量超过标志所示数值的车辆通行。此标志设在需要限制车辆质量的桥梁两端。以图为例：装载总质量不得超过10t。"
    }, {
        title: "停车检查",
        image: "1040.gif",
        desc: "表示机动车必须停车接受检查。此标志设在关卡将近处，以便要求车辆接受检查或缴费等手续。标志中可加注说明检查事项。"
    }, {
        title: "限制轴重",
        image: "1041.gif",
        desc: "表示禁止轴重超过标志所示数值的车辆通行。此标志设在需要限制车辆轴重的桥梁两端。以图为例：限制车辆轴重量不得超过7t。"
    }, {
        title: "停车让行",
        image: "1042.gif",
        desc: "表示车辆必须在停止线以外停车了望，确认安全后，才准许通行。停车让行标志在下列情况下设置：(1)与交通流量较大的干路平交的支路路口；(2)无人看守的铁路道口；(3)其他需要设置的地方。"
    }, {
        title: "禁止运输危险物品车辆驶入",
        image: "1043.gif",
        desc: "表示禁止运输危险物品车辆驶入。"
    }, {
        title: "海关",
        image: "1044.gif",
        desc: "表示道路前方是海关，所有机动车应停车后方可通过。设在道路上机动车需停车接受海关检查方可通过的地点。"
    }, {
        title: "区域禁止长时停车",
        image: "1045.gif",
        desc: "表示区域内禁止车辆的某种行为。设在禁止区域的所有入口处(禁止)。"
    }, {
        title: "区域禁止长时停车解除",
        image: "1046.gif",
        desc: "表示区域禁止长时停车解除。设在禁止区域的所有出口处(禁止解除)。 "
    }, {
        title: "区域禁止停车",
        image: "1047.gif",
        desc: "表示区域内禁止车辆的某种行为。设在禁止区域的所有入口处(禁止)。"
    }, {
        title: "区域禁止停车解除",
        image: "1048.gif",
        desc: "表示区域禁止停车解除。设在禁止区域的所有出口处(禁止解除)。"
    }, {
        title: "区域限制速度",
        image: "1049.gif",
        desc: "表示区域内禁止车辆的某种行为。设在禁止区域的所有入口处(禁止)。"
    }, {
        title: "区域限制速度解除",
        image: "1050.gif",
        desc: "表示区域限制速度解除。设在禁止区域的所有出口处(禁止解除)。"
    } ]
}, {
    title: "警告标志",
    list: [ {
        title: "十字交叉",
        image: "2001.gif",
        desc: "除了基本形十字路口外，还有部分变异的十字路口，如：五路交叉路口、变形十字路口、变形五路交叉路口等。五路以上的路口均按十字路口对待。"
    }, {
        title: "Y形交叉",
        image: "2002.gif",
        desc: "设在Y形路口以前的适当位置。"
    }, {
        title: "反向弯路",
        image: "2003.gif",
        desc: "此标志设在两个相邻的方向相反的弯路前适当位置。"
    }, {
        title: "两侧变窄",
        image: "2004.gif",
        desc: "车行道两侧变窄主要指沿道路中心线对城缩窄的道路；此标志设在窄路以前适当位置。"
    }, {
        title: "T形交叉",
        image: "2005.gif",
        desc: "丁字形标志原则上设在与交叉口形状相符的道路上。右侧丁字路口，此标志设在进入T字路口以前的适当位置。"
    }, {
        title: "环形交叉",
        image: "2006.gif",
        desc: "有的环形交叉路口，由于受线形限制或障碍物阻挡，此标志设在面对来车的路口的正面。"
    }, {
        title: "连续弯路",
        image: "2007.gif",
        desc: "此标志设在有连续三个以上弯路的道路以前适当位置。"
    }, {
        title: "右侧变窄",
        image: "2008.gif",
        desc: "车行道右侧缩窄。此标志设在窄路以前适当位置。"
    }, {
        title: "T形交叉",
        image: "2009.gif",
        desc: "丁字形标志原则上设在与交叉口形状相符的道路上。左侧丁字路口此标志设在进入丁字路口以前的适当位置。"
    }, {
        title: "向左急弯路",
        image: "2010.gif",
        desc: "向左急弯路标志设在左急转弯的道路前方适当位置。"
    }, {
        title: "上陡坡",
        image: "2011.gif",
        desc: "此标志设在纵坡度在7%和市区纵坡度在大于4%的陡坡道路前适当位置。"
    }, {
        title: "左侧变窄",
        image: "2012.gif",
        desc: "车行道左侧缩窄。此标志设在窄路以前适当位置。"
    }, {
        title: "T形交叉",
        image: "2013.gif",
        desc: "丁字形标志原则上设在与交叉口形状相符的道路上。此标志设在进入T字路口以前的适当位置。"
    }, {
        title: "向右急弯路",
        image: "2014.gif",
        desc: "向右急弯路标志，设在右急转弯的道路前方适当位置。"
    }, {
        title: "下陡坡",
        image: "2015.gif",
        desc: "此标志设在纵坡度在7%和市区纵坡度在大于4%的陡坡道路前适当位置。"
    }, {
        title: "窄桥",
        image: "2016.gif",
        desc: "此标志设在桥面宽度小于路面宽度的窄桥以前适当位置。"
    }, {
        title: "双向交通",
        image: "2017.gif",
        desc: "双向行驶的道路上，采用天然的或人工的隔离措施，把上下行交通完全分离，由于某种原因（施工、桥、隧道）形成无隔离的双向车道时，须设置此标志。"
    }, {
        title: "注意信号灯",
        image: "2018.gif",
        desc: "此标志设在不易发现前方位信号灯控制的路口前适当位置。"
    }, {
        title: "易滑",
        image: "2019.gif",
        desc: "此标志设在路面的摩擦系数不能满足相应行驶速度下要求紧急刹车距离的路段前适当位置。行驶至此路段必须减速慢行。"
    }, {
        title: "堤坝路",
        image: "2020.gif",
        desc: "此标志设在沿水库、湖泊、河流等堤坝路以前适当位置。"
    }, {
        title: "注意行人",
        image: "2021.gif",
        desc: "一般设在郊外道路上划有人行横道的前方。城市道路上因人行横道线较多，可根据实际需要设置。"
    }, {
        title: "注意落石",
        image: "2022.gif",
        desc: "此标志设在左侧有落石危险的傍山路段之前适当位置。"
    }, {
        title: "傍山险路",
        image: "2023.gif",
        desc: "此标志设在山区地势险要路段（道路外侧位陡壁、悬崖危险的路段）以前适当位置。"
    }, {
        title: "村庄",
        image: "2024.gif",
        desc: "此标志设在不易发现前方有村庄或小城镇的路段以前适当位置。"
    }, {
        title: "注意儿童",
        image: "2025.gif",
        desc: "此标志设在小学、幼儿园、少年宫、儿童游乐场等儿童频繁出入的场所或通道处。"
    }, {
        title: "注意落石",
        image: "2026.gif",
        desc: "此标志设在右侧有落石危险的傍山路段之前适当位置。"
    }, {
        title: "傍山险路",
        image: "2027.gif",
        desc: "此标志设在山区地势险要路段（道路外侧位陡壁、悬崖危险的路段）以前适当位置。"
    }, {
        title: "隧道",
        image: "2028.gif",
        desc: "此标志设在进入隧道前的适当位置。"
    }, {
        title: "注意牲畜",
        image: "2029.gif",
        desc: "此标志设在经常有牲畜活动的路段特别是视线不良的路段以前适当位置。"
    }, {
        title: "注意横风",
        image: "2030.gif",
        desc: "此标志设在经常有很强的侧风并有必要引起注意的路段前适当位置。"
    }, {
        title: "堤坝路",
        image: "2031.gif",
        desc: "此标志设在沿水库、湖泊、河流等堤坝路以前适当位置。"
    }, {
        title: "渡口",
        image: "2032.gif",
        desc: "此标志设在汽车渡口以前适当位置。特别是有的渡口地形较位复杂、道路条件较差，使用此标志能引起驾驶员的谨慎驾驶、注意安全。"
    }, {
        title: "驼峰桥",
        image: "2033.gif",
        desc: "此标志设在注意前方是拱度较大，不易发现对方来车，应靠右侧行驶并应减速慢行。"
    }, {
        title: "无人看守铁路道口",
        image: "2034.gif",
        desc: "此标志设在道口以前适当位置。"
    }, {
        title: "左右绕行",
        image: "2035.gif",
        desc: "用以告示前方道路有障碍物，车辆应按标志指示减速慢行，绕行通过。"
    }, {
        title: "注意危险",
        image: "2036.gif",
        desc: "用以提醒车辆驾驶员谨慎慢行。"
    }, {
        title: "路面不平",
        image: "2037.gif",
        desc: "此标志设在路面不平的路段以前适当位置。"
    }, {
        title: "注意非机动车",
        image: "2038.gif",
        desc: "此标志设在混合行驶的道路并经常有非机动车横穿、出入的地点以前适当位置。"
    }, {
        title: "左侧绕行",
        image: "2039.gif",
        desc: "用以告示前方道路有障碍物，车辆应按标志指示减速慢行，左侧绕行通过。"
    }, {
        title: "无人看守铁路道口",
        image: "2040.gif",
        desc: "表示距铁道口的距离，一道斜杠距离道口50米。"
    }, {
        title: "过水路面",
        image: "2041.gif",
        desc: "此标志设在过水路面或漫水桥路段以前适当位置。"
    }, {
        title: "事故易发路段",
        image: "2042.gif",
        desc: "此标志设在交通事故易发路段以前适当位置。"
    }, {
        title: "右侧绕行",
        image: "2043.gif",
        desc: "用以告示前方道路有障碍物，车辆应按标志指示减速慢行，右侧绕行通过。"
    }, {
        title: "无人看守铁路道口",
        image: "2044.gif",
        desc: "表示距铁道口的距离，二道斜杠距离道口100米。"
    }, {
        title: "有人看守铁路道口",
        image: "2045.gif",
        desc: "此标志设在不易发现的道口以前适当位置。"
    }, {
        title: "慢行",
        image: "2046.gif",
        desc: "此标志设在前方需要减速慢行的路段以前适当位置。"
    }, {
        title: "施工标志",
        image: "2047.gif",
        desc: "用以告示前方道路施工，车辆应减速慢行或绕道行驶。"
    }, {
        title: "无人看守铁路道口",
        image: "2048.gif",
        desc: "表示距铁道口的距离，三道斜杠距离道口150米。"
    }, {
        title: "交叉路口",
        image: "2049.gif",
        desc: "用以警告车辆驾驶人谨慎慢行，注意横向来车。"
    }, {
        title: "连续下坡",
        image: "2050.gif",
        desc: "用以提醒车辆驾驶人小心驾驶。"
    }, {
        title: "注意野生动物",
        image: "2051.gif",
        desc: "用以提醒车辆驾驶人注意慢行。"
    }, {
        title: "路面高突",
        image: "2052.gif",
        desc: "用以提醒车辆驾驶人减速慢行。"
    }, {
        title: "路面低洼标志",
        image: "2053.gif",
        desc: "用以提醒车辆驾驶人减速慢行。设在路面突然低洼以前适当位置。"
    }, {
        title: "叉形符号",
        image: "2054.gif",
        desc: "表示多股铁道与道路交叉，设在铁路道口标志上端"
    }, {
        title: "注意残疾人",
        image: "2055.gif",
        desc: "用以提醒车辆驾驶人减速慢行，注意残疾人。"
    }, {
        title: "建议减速",
        image: "2056.gif",
        desc: "用以提醒车辆驾驶人以建议的速度行驶，设在弯道、出口、匝道的适当位置。"
    }, {
        title: "隧道开车灯",
        image: "2057.gif",
        desc: "用以警告车辆驾驶人进入隧道打开前照灯，注意行驶。"
    }, {
        title: "注意潮汐车道",
        image: "2058.gif",
        desc: "用以警告车辆驾驶人注意前方为潮汐车道。"
    }, {
        title: "避险车道",
        image: "2059.gif",
        desc: "设置了避险车道的道路上。在其前方适当位置应至少设置一块避险车道标志。"
    }, {
        title: "注意合流",
        image: "2060.gif",
        desc: "用以警告车辆驾驶人注意前方有车辆汇合进来。"
    }, {
        title: "注意合流",
        image: "2061.gif",
        desc: "用以警告车辆驾驶人注意前方有车辆汇合进来。"
    }, {
        title: "丁字平面交叉",
        image: "2062.gif",
        desc: "用以警告车辆驾驶人注意前方平面交叉的被交道路是分离式道路。"
    }, {
        title: "十字平面交叉",
        image: "2063.gif",
        desc: "用以警告车辆驾驶人注意前方平面交叉的被交道路是分离式道路。"
    }, {
        title: "注意保持车距",
        image: "2064.gif",
        desc: "用以警告车辆驾驶人注意和前车保持安全距离。"
    }, {
        title: "注意前方车辆排队",
        image: "2065.gif",
        desc: "用以警告车辆驾驶人注意前方车辆排队。"
    }, {
        title: "注意不利气象条件",
        image: "2066.gif",
        desc: "用以警告车辆驾驶人注意不利气象条件谨慎驾驶。"
    }, {
        title: "注意路面结冰",
        image: "2067.gif",
        desc: "用以警告车辆驾驶人注意路面结冰谨慎驾驶。"
    }, {
        title: "注意雾天",
        image: "2068.gif",
        desc: "用以警告车辆驾驶人注意雾天谨慎驾驶。"
    }, {
        title: "注意雨（雪）天",
        image: "2069.gif",
        desc: "用以警告车辆驾驶人注意雨（雪）天谨慎驾驶。"
    } ]
}, {
    title: "指示标志",
    list: [ {
        title: "直行",
        image: "3001.gif",
        desc: "表示只准一切车辆直行。此标志设在直行的路口以前适当位置。"
    }, {
        title: "直行和向右转弯",
        image: "3002.gif",
        desc: "表示只准一切车辆直行和向右转弯。此标志设在车辆必须直行和向右转弯的路口以前适当位置。"
    }, {
        title: "立交直行和左转弯行驶",
        image: "3003.gif",
        desc: "表示车辆在立交处可以直行和按图示路线左转弯行驶。此标志设在立交左转弯出口处适当位置。"
    }, {
        title: "鸣喇叭",
        image: "3004.gif",
        desc: "表示机动车行至该标志处必须鸣喇叭。此标志设在公路的急转弯处、陡坡等视线不良路段的起点。"
    }, {
        title: "向左转弯",
        image: "3005.gif",
        desc: "表示只准一切车辆向左转弯。此标志设在车辆必须向左转弯的路口以前适当位置。"
    }, {
        title: "向左和向右转弯",
        image: "3006.gif",
        desc: "表示只准一切车辆向左和向右转弯。此标志设在车辆必须向左和向右转弯的路口以前适当位置。"
    }, {
        title: "立交直行和右转弯行驶",
        image: "3007.gif",
        desc: "表示车辆在立交处可以直行和按图示路线右转弯行驶。此标志设在立交右转弯出口处适当位置。"
    }, {
        title: "最低限速",
        image: "3008.gif",
        desc: "表示机动车驶入前方道路之最低时速限制。此标志设在高速公路或其他道路限速路段的起点。"
    }, {
        title: "向右转弯",
        image: "3009.gif",
        desc: "表示只准一切车辆向右转弯。此标志设在车辆必须向右转弯的路口以前适当位置。"
    }, {
        title: "靠右侧道路行驶",
        image: "3010.gif",
        desc: "表示只准一切车辆靠右侧道路行驶。此标志设在车辆必须靠右侧行驶的路口以前适当位置。"
    }, {
        title: "环岛行驶",
        image: "3011.gif",
        desc: "表示只准车辆靠右环行。此标志设在环岛面向路口来车方向适当位置。"
    }, {
        title: "单行路向左或向右",
        image: "3012.gif",
        desc: "表示一切车辆向左或向右单向行驶。此标志设在单行路的路口和入口处的适当位置。"
    }, {
        title: "直行和向左转弯",
        image: "3013.gif",
        desc: "表示只准一切车辆直行和向左转弯。此标志设在车辆必须直行和向左转弯的路口以前适当位置。"
    }, {
        title: "靠左侧道路行驶",
        image: "3014.gif",
        desc: "表示只准一切车辆靠左侧道路行驶。此标志设在车辆必须靠左侧行驶的路口以前适当位置。"
    }, {
        title: "步行",
        image: "3015.gif",
        desc: "表示该街道只供步行。此标志设在步行街的两端。"
    }, {
        title: "单行路 直行",
        image: "3016.gif",
        desc: "表示一切车辆单向行驶。此标志设在单行路的路口和入口处的适当位置。"
    }, {
        title: "干路先行",
        image: "3017.gif",
        desc: "表示干路先行，此标志设在车道以前适当位置。"
    }, {
        title: "直行车道",
        image: "3018.gif",
        desc: "表示车道的行驶方向。此标志设在导向车道以前适当位置。"
    }, {
        title: "机动车行驶",
        image: "3019.gif",
        desc: "表示车道机动车行驶。此标志设在道路或车道的起点及交叉路口入口处前适当位置。"
    }, {
        title: "允许掉头",
        image: "3020.gif",
        desc: "表示允许掉头。此标志设在允许机动车掉头路段的起点和路口以前适当位置。"
    }, {
        title: "会车先行",
        image: "3021.gif",
        desc: "表示会车先行，此标志设在车道以前适当位置。"
    }, {
        title: "直行和右转合用车道",
        image: "3022.gif",
        desc: "表示车道的行驶方向。此标志设在导向车道以前适当位置。"
    }, {
        title: "机动车车道",
        image: "3023.gif",
        desc: "表示该道路或车道专供机动车行驶。此标志设在道路或车道的起点及交叉路口入口处前适当位置。"
    }, {
        title: "人行横道",
        image: "3024.gif",
        desc: "表示该处为专供行人横穿马路的通道。此标志设在人行横道的两侧。"
    }, {
        title: "分向行驶车道",
        image: "3025.gif",
        desc: "表示车道的行驶方向。此标志设在导向车道以前适当位置。"
    }, {
        title: "非机动车行驶",
        image: "3026.gif",
        desc: "表示非机动车行驶。此标志设在道路或车道的起点及交叉路口入口处前适当位置。"
    }, {
        title: "右转车道",
        image: "3027.gif",
        desc: "表示车道的行驶方向。此标志设在导向车道以前适当位置。"
    }, {
        title: "公交线路专用车道",
        image: "3028.gif",
        desc: "表示该车道专供本线路行驶的公交车辆行驶。此标志设在进入该车道的起点及各交叉口入口处以前适当位置。"
    }, {
        title: "非机动车车道",
        image: "3029.gif",
        desc: "表示该道路或车道专供非机动车行驶。此标志设在道路或车道的起点及交叉路口入口处前适当位置。"
    }, {
        title: "掉头和左转合用车道",
        image: "3030.gif",
        desc: "表示车道的行驶方向。"
    }, {
        title: "快速公交系统专用车道",
        image: "3031.gif",
        desc: "表示该车道专供BRT车辆行驶。"
    }, {
        title: "多乘员车辆专用车道",
        image: "3032.gif",
        desc: "表示该车道只供多乘员的车辆行驶。"
    } ]
}, {
    title: "指路标志",
    list: [ {
        title: "地名",
        image: "4001.gif",
        desc: ""
    }, {
        title: "著名地点",
        image: "4002.gif",
        desc: ""
    }, {
        title: "行政区划分界",
        image: "4003.gif",
        desc: ""
    }, {
        title: "道路管理分界",
        image: "4004.gif",
        desc: ""
    }, {
        title: "国道编号",
        image: "4005.gif",
        desc: ""
    }, {
        title: "省道编号",
        image: "4006.gif",
        desc: ""
    }, {
        title: "县道编号",
        image: "4007.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4008.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4009.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4010.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4011.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4012.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4013.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4014.gif",
        desc: ""
    }, {
        title: "行驶方向",
        image: "4015.gif",
        desc: ""
    }, {
        title: "互通式立交",
        image: "4016.gif",
        desc: ""
    }, {
        title: "交叉路口预告",
        image: "4017.gif",
        desc: ""
    }, {
        title: "十字交叉路口",
        image: "4018.gif",
        desc: ""
    }, {
        title: "十字交叉路口",
        image: "4019.gif",
        desc: ""
    }, {
        title: "十字交叉路口",
        image: "4020.gif",
        desc: ""
    }, {
        title: "十字交叉路口",
        image: "4021.gif",
        desc: ""
    }, {
        title: "丁字交叉路口",
        image: "4022.gif",
        desc: ""
    }, {
        title: "丁字交叉路口",
        image: "4023.gif",
        desc: ""
    }, {
        title: "环形交叉路口",
        image: "4024.gif",
        desc: ""
    }, {
        title: "环形交叉路口",
        image: "4025.gif",
        desc: ""
    }, {
        title: "交叉路口预告",
        image: "4026.gif",
        desc: ""
    }, {
        title: "互通式立交",
        image: "4027.gif",
        desc: ""
    }, {
        title: "互通式立交",
        image: "4028.gif",
        desc: ""
    }, {
        title: "互通式立交",
        image: "4029.gif",
        desc: ""
    }, {
        title: "分岔处",
        image: "4030.gif",
        desc: ""
    }, {
        title: "地点距离标志",
        image: "4031.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4032.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4033.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4034.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4035.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4036.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4037.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4038.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4039.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4040.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4041.gif",
        desc: ""
    }, {
        title: "地点识别标志",
        image: "4042.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4043.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4044.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4045.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4046.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4047.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4048.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4049.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4050.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4051.gif",
        desc: ""
    }, {
        title: "告示牌",
        image: "4052.gif",
        desc: ""
    }, {
        title: "停车场",
        image: "4053.gif",
        desc: ""
    }, {
        title: "停车场",
        image: "4054.gif",
        desc: ""
    }, {
        title: "停车场",
        image: "4055.gif",
        desc: ""
    }, {
        title: "避车道",
        image: "4056.gif",
        desc: ""
    }, {
        title: "人行天桥",
        image: "4057.gif",
        desc: ""
    }, {
        title: "绕行标志",
        image: "4058.gif",
        desc: ""
    }, {
        title: "绕行标志",
        image: "4059.gif",
        desc: ""
    }, {
        title: "绕行标志",
        image: "4060.gif",
        desc: ""
    }, {
        title: "此路不通",
        image: "4061.gif",
        desc: ""
    }, {
        title: "残疾人专用设施",
        image: "4062.gif",
        desc: ""
    }, {
        title: "右侧通行",
        image: "4063.gif",
        desc: ""
    }, {
        title: "左侧通行",
        image: "4064.gif",
        desc: ""
    }, {
        title: "两侧通行",
        image: "4065.gif",
        desc: ""
    }, {
        title: "起点",
        image: "x10.gif",
        desc: ""
    }, {
        title: "终点预告",
        image: "x11.gif",
        desc: ""
    }, {
        title: "终点提示",
        image: "x12.gif",
        desc: ""
    }, {
        title: "终点",
        image: "x13.gif",
        desc: ""
    }, {
        title: "下一出口",
        image: "x14.gif",
        desc: ""
    }, {
        title: "下一出口",
        image: "x15.gif",
        desc: ""
    }, {
        title: "出口编号预告",
        image: "x16.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x17.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x18.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x19.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x20.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x22.gif",
        desc: ""
    }, {
        title: "出口预告",
        image: "x23.gif",
        desc: ""
    }, {
        title: "出口",
        image: "x24.gif",
        desc: ""
    }, {
        title: "出口",
        image: "x25.gif",
        desc: ""
    }, {
        title: "出口",
        image: "x26.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x27.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x28.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x29.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x33.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x34.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x35.gif",
        desc: ""
    }, {
        title: "地点方向",
        image: "x36.gif",
        desc: ""
    }, {
        title: "地点距离",
        image: "x37.gif",
        desc: ""
    }, {
        title: "收费站预告",
        image: "x38.gif",
        desc: ""
    }, {
        title: "收费站预告",
        image: "x39.gif",
        desc: ""
    }, {
        title: "收费站预告",
        image: "x40.gif",
        desc: ""
    }, {
        title: "收费站",
        image: "x41.gif",
        desc: ""
    }, {
        title: "紧急电话",
        image: "x42.gif",
        desc: ""
    }, {
        title: "电话立置指示",
        image: "x43.gif",
        desc: ""
    }, {
        title: "电话立置指示",
        image: "x44.gif",
        desc: ""
    }, {
        title: "加油站",
        image: "x45.gif",
        desc: ""
    }, {
        title: "紧急停车带",
        image: "x46.gif",
        desc: ""
    }, {
        title: "服务区预告",
        image: "x47.gif",
        desc: ""
    }, {
        title: "服务区预告",
        image: "x48.gif",
        desc: ""
    }, {
        title: "服务区预告",
        image: "x49.gif",
        desc: ""
    }, {
        title: "服务区预告",
        image: "x50.gif",
        desc: ""
    }, {
        title: "停车区预告",
        image: "x51.gif",
        desc: ""
    }, {
        title: "停车区预告",
        image: "x52.gif",
        desc: ""
    }, {
        title: "停车区预告",
        image: "x53.gif",
        desc: ""
    }, {
        title: "停车区预告",
        image: "x54.gif",
        desc: ""
    }, {
        title: "停车区预告",
        image: "x55.gif",
        desc: ""
    }, {
        title: "停车场",
        image: "x56.gif",
        desc: ""
    }, {
        title: "爬坡车道",
        image: "x57.jpg",
        desc: ""
    }, {
        title: "爬坡车道",
        image: "x58.gif",
        desc: ""
    }, {
        title: "爬坡车道",
        image: "x59.gif",
        desc: ""
    }, {
        title: "爬坡车道",
        image: "x60.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "x61.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "x62.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "x63.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "x64.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "x65.gif",
        desc: ""
    }, {
        title: "道路交通信息",
        image: "x66.gif",
        desc: ""
    }, {
        title: "道路交通信息",
        image: "x67.gif",
        desc: ""
    }, {
        title: "道路交通信息",
        image: "x68.gif",
        desc: ""
    }, {
        title: "里程牌",
        image: "x69.gif",
        desc: ""
    }, {
        title: "百米牌",
        image: "x70.jpg",
        desc: ""
    }, {
        title: "分流",
        image: "x71.jpg",
        desc: ""
    }, {
        title: "合流",
        image: "x72.jpg",
        desc: ""
    }, {
        title: "线形诱导标基本单元 ",
        image: "x73.jpg",
        desc: ""
    }, {
        title: "基本单元组合使用",
        image: "x74.jpg",
        desc: ""
    }, {
        title: "乡道编号",
        image: "4066.gif",
        desc: "用以确认当前所行驶的道路信息及前方通往方向信息。指示当前公路编号，设在乡道上交叉路口后30m--50m的位置。 "
    }, {
        title: "地点识别标志",
        image: "4067.gif",
        desc: "为道路使用者提供各种重要场所的识别和指向，设在所标识地点前适当位置。 "
    }, {
        title: "人行地下通道",
        image: "4068.gif",
        desc: "用于指引行人通往地下通道入口的位置。设在地下通道入口附近。"
    }, {
        title: "观景台",
        image: "4069.gif",
        desc: "设置在路侧可供驾驶员停车观景地带的两侧。"
    }, {
        title: "交通监控设备",
        image: "4070.gif",
        desc: "设在设置了图像采集等交通监控设备的路段适当位置。 "
    }, {
        title: "休息区",
        image: "4071.gif",
        desc: "一般设置在路侧休息区的两侧。"
    }, {
        title: "车道数变少",
        image: "4072.gif",
        desc: "用于表示前方车道数量变少，需提高警惕。设在变化点前适当位置。 "
    }, {
        title: "车道数变少",
        image: "4073.gif",
        desc: "用于表示前方车道数量变少，需提高警惕。设在变化点前适当位置。 "
    }, {
        title: "车道数增加",
        image: "4074.gif",
        desc: "用以提示车辆驾驶人员车道数量增加，需要谨慎驾驶，设在车道数量增加断面前适当位置。"
    }, {
        title: "隧道出口距离预告",
        image: "4075.gif",
        desc: "用于指示到前方隧道出口的距离。设在长度超过3000m的特长隧道内，从距离隧道出口2000m处开始每500m设置一块，直至隧道出口。该标志一般设置在隧道侧壁上。"
    }, {
        title: "特殊天气建议速度",
        image: "4076.gif",
        desc: "用以提醒驾驶员在雨、雪、雾等特殊天气下，以建议速度行驶，和白色半圆状车距确认线配合使用。"
    }, {
        title: "停车领卡",
        image: "4077.gif",
        desc: "用以提示停车领卡，设在进入高速公路或城市快速路收费站入口一侧的适当位置。"
    }, {
        title: "救援电话",
        image: "4078.gif",
        desc: "用于指示救援电话号码，没有设置紧急电话的高速公路上应设置救援电话标志。标志上号码为示例。"
    }, {
        title: "ETC车道指示",
        image: "4079.gif",
        desc: "用于指示电子不停车收费车道，设在收费广场渐变段起点前300m处。表示单向3个收费车道时ETC车道指示标志。"
    }, {
        title: "设置在指路标志版面中的方向",
        image: "4080.gif",
        desc: "与指路标志一起使用，用于指示道路地理方向。适用于交叉路口处。"
    }, {
        title: "设置在指路标志版面中的方向",
        image: "4081.gif",
        desc: "与指路标志一起使用，用于指示道路地理方向。适用于立体交叉出口匝道处。"
    }, {
        title: "设置在指路标志版面中的方向",
        image: "4082.gif",
        desc: "与指路标志一起使用，用于指示道路地理方向。适用于立体交叉出口匝道处。"
    } ]
}, {
    title: "旅游区标志",
    list: [ {
        title: "旅游区方向",
        image: "5001.gif",
        desc: ""
    }, {
        title: "旅游区距离",
        image: "5002.gif",
        desc: ""
    }, {
        title: "问询处",
        image: "5003.gif",
        desc: ""
    }, {
        title: "徒步",
        image: "5004.gif",
        desc: ""
    }, {
        title: "索道",
        image: "5005.gif",
        desc: ""
    }, {
        title: "野营地",
        image: "5006.gif",
        desc: ""
    }, {
        title: "营火",
        image: "5007.gif",
        desc: ""
    }, {
        title: "游戏场",
        image: "5008.gif",
        desc: ""
    }, {
        title: "骑马",
        image: "5009.gif",
        desc: ""
    }, {
        title: "钓鱼",
        image: "5010.gif",
        desc: ""
    }, {
        title: "高尔夫球",
        image: "5011.gif",
        desc: ""
    }, {
        title: "潜水",
        image: "5012.gif",
        desc: ""
    }, {
        title: "游泳",
        image: "5013.gif",
        desc: ""
    }, {
        title: "划船",
        image: "5014.gif",
        desc: ""
    }, {
        title: "冬季浏览区",
        image: "5015.gif",
        desc: ""
    }, {
        title: "滑雪",
        image: "5016.gif",
        desc: ""
    }, {
        title: "滑冰",
        image: "5017.gif",
        desc: ""
    } ]
}, {
    title: "道路施工安全标志",
    list: [ {
        title: "前方1km道路施工",
        image: "6001.gif",
        desc: ""
    }, {
        title: "前方300m道路施工",
        image: "6002.gif",
        desc: ""
    }, {
        title: "道路施工",
        image: "6003.gif",
        desc: ""
    }, {
        title: "前方1km道路封闭",
        image: "6004.gif",
        desc: ""
    }, {
        title: "前方300m道路封闭",
        image: "6005.gif",
        desc: ""
    }, {
        title: "道路封闭",
        image: "6006.gif",
        desc: ""
    }, {
        title: "前方1km右道封闭",
        image: "6007.gif",
        desc: ""
    }, {
        title: "前方300m右道封闭",
        image: "6008.gif",
        desc: ""
    }, {
        title: "右道封闭",
        image: "6009.gif",
        desc: ""
    }, {
        title: "前方1km左道封闭",
        image: "6010.gif",
        desc: ""
    }, {
        title: "前方300m左道封闭",
        image: "6011.gif",
        desc: ""
    }, {
        title: "左道封闭",
        image: "6012.gif",
        desc: ""
    }, {
        title: "前方1km中间封闭",
        image: "6013.gif",
        desc: ""
    }, {
        title: "前方300m中间封闭",
        image: "6014.gif",
        desc: ""
    }, {
        title: "中间封闭",
        image: "6015.gif",
        desc: ""
    }, {
        title: "车辆慢行",
        image: "6016.gif",
        desc: ""
    }, {
        title: "向左改道",
        image: "6017.gif",
        desc: ""
    }, {
        title: "向右改道",
        image: "6018.gif",
        desc: ""
    }, {
        title: "向左行驶",
        image: "6019.gif",
        desc: ""
    }, {
        title: "向右行驶",
        image: "6020.gif",
        desc: ""
    }, {
        title: "道口标柱",
        image: "6021.gif",
        desc: ""
    }, {
        title: "锥形交通标",
        image: "6022.gif",
        desc: ""
    }, {
        title: "锥形交通标",
        image: "6023.gif",
        desc: ""
    }, {
        title: "移动性施工标志",
        image: "6024.gif",
        desc: ""
    }, {
        title: "施工路栏",
        image: "6025.gif",
        desc: ""
    }, {
        title: "施工路栏",
        image: "6026.gif",
        desc: ""
    } ]
}, {
    title: "辅助标志",
    list: [ {
        title: "时间范围",
        image: "7001.gif",
        desc: ""
    }, {
        title: "时间范围",
        image: "7002.gif",
        desc: ""
    }, {
        title: "除公共汽车外",
        image: "7003.gif",
        desc: ""
    }, {
        title: "机动车",
        image: "7004.gif",
        desc: ""
    }, {
        title: "货车",
        image: "7005.gif",
        desc: ""
    }, {
        title: "货车、拖拉机",
        image: "7006.gif",
        desc: ""
    }, {
        title: "向前200m",
        image: "7007.gif",
        desc: ""
    }, {
        title: "向左100m",
        image: "7008.gif",
        desc: ""
    }, {
        title: "向左、向右各50m",
        image: "7009.gif",
        desc: ""
    }, {
        title: "向右100m",
        image: "7010.gif",
        desc: ""
    }, {
        title: "某区域内",
        image: "7011.gif",
        desc: ""
    }, {
        title: "学校",
        image: "7012.gif",
        desc: ""
    }, {
        title: "海关",
        image: "7013.gif",
        desc: ""
    }, {
        title: "事故",
        image: "7014.gif",
        desc: ""
    }, {
        title: "坍方",
        image: "7015.gif",
        desc: ""
    }, {
        title: "组合",
        image: "7016.gif",
        desc: ""
    }, {
        title: "私人专属",
        image: "7017.gif",
        desc: "根据需要，对某些标志规定车辆的种类、属性。"
    }, {
        title: "教练车行驶路线",
        image: "7018.gif",
        desc: "表示警告、禁令理由。"
    }, {
        title: "驾驶考试路线",
        image: "7019.gif",
        desc: "表示警告、禁令理由。"
    }, {
        title: "严禁酒后驾车标志",
        image: "7020.gif",
        desc: "提醒驾驶员不要酒后驾车。"
    }, {
        title: "严禁乱扔弃物标志",
        image: "7021.gif",
        desc: "提醒驾乘人员不要向车外抛洒物品。"
    }, {
        title: "急弯减速慢行标志",
        image: "7022.gif",
        desc: "提醒驾驶员急弯减速行驶。"
    }, {
        title: "急弯下坡减速慢行标志",
        image: "7023.gif",
        desc: "提醒驾驶员急弯减速行驶。"
    }, {
        title: "系安全带标志",
        image: "7024.gif",
        desc: "提醒机动车驾驶员、乘坐人员应按规定使用安全带。"
    }, {
        title: "大型车靠右",
        image: "7025.gif",
        desc: "提醒行驶速度较慢的大型车辆靠右行驶。"
    }, {
        title: "驾驶时禁用手机标志",
        image: "7026.gif",
        desc: "提醒机动车驾驶员驾车时不要使用手持电话。"
    }, {
        title: "校车停靠站点",
        image: "7027.gif",
        desc: "提醒机动车驾驶员注意此处为校车停靠站点。"
    } ]
}, {
    title: "禁止标线",
    list: [ {
        title: "中心黄色双实线",
        image: "8001.gif",
        desc: ""
    }, {
        title: "中心黄色虚实线",
        image: "8002.gif",
        desc: ""
    }, {
        title: "三车道标线",
        image: "8003.gif",
        desc: ""
    }, {
        title: "禁止变换车道线",
        image: "8004.gif",
        desc: ""
    }, {
        title: "禁止路边长时停放车辆线",
        image: "8005.gif",
        desc: ""
    }, {
        title: "禁止路边临时或长时停放车辆线",
        image: "8006.gif",
        desc: ""
    }, {
        title: "信号灯路口的停止线",
        image: "8007.gif",
        desc: ""
    }, {
        title: "停止线",
        image: "8008.gif",
        desc: ""
    }, {
        title: "停车让行线",
        image: "8009.gif",
        desc: ""
    }, {
        title: "减速让行线",
        image: "8010.gif",
        desc: ""
    }, {
        title: "非机动车禁驶区标线",
        image: "8011.gif",
        desc: ""
    }, {
        title: "禁驶区标线尺寸  单位:cm",
        image: "8012.gif",
        desc: ""
    }, {
        title: "复杂行驶条件丁字路口导流线",
        image: "8013.gif",
        desc: ""
    }, {
        title: "复杂行驶条件十字路口导流线",
        image: "8014.gif",
        desc: ""
    }, {
        title: "斜交丁字路口导流线",
        image: "8015.gif",
        desc: ""
    }, {
        title: "不规则路口导流线",
        image: "8016.gif",
        desc: ""
    }, {
        title: "Y形路口导流线",
        image: "8017.gif",
        desc: ""
    }, {
        title: "支路口主干道相交路口导流线",
        image: "8018.gif",
        desc: ""
    }, {
        title: "中心圈",
        image: "8019.gif",
        desc: ""
    }, {
        title: "中心圈",
        image: "8020.gif",
        desc: ""
    }, {
        title: "网状线",
        image: "8021.gif",
        desc: ""
    }, {
        title: "简化网状线",
        image: "8022.gif",
        desc: ""
    }, {
        title: "专用车道线",
        image: "8023.gif",
        desc: ""
    }, {
        title: "禁止掉头",
        image: "8024.gif",
        desc: ""
    } ]
}, {
    title: "警告标线",
    list: [ {
        title: "三车道缩减为双车道",
        image: "9001.gif",
        desc: ""
    }, {
        title: "四车道缩减为双车道",
        image: "9002.gif",
        desc: ""
    }, {
        title: "四车道缩减为三车道",
        image: "9003.gif",
        desc: ""
    }, {
        title: "四车道缩减为两车道",
        image: "9004.gif",
        desc: ""
    }, {
        title: "三车道斑马线过渡",
        image: "9005.gif",
        desc: ""
    }, {
        title: "双向两车道改变为双向四车道",
        image: "9006.gif",
        desc: ""
    }, {
        title: "双车道中间有障碍",
        image: "9007.gif",
        desc: ""
    }, {
        title: "四车道中间有障碍",
        image: "9008.gif",
        desc: ""
    }, {
        title: "同方向二车道中间有障碍",
        image: "9009.gif",
        desc: ""
    }, {
        title: "铁路平交道口标线",
        image: "9010.gif",
        desc: ""
    }, {
        title: "减速标线",
        image: "9011.gif",
        desc: ""
    }, {
        title: "收费广场减速标线设置例",
        image: "9012.gif",
        desc: ""
    }, {
        title: "立面标记",
        image: "9013.gif",
        desc: ""
    } ]
}, {
    title: "指示标线",
    list: [ {
        title: "双向两车道路面中心线",
        image: "a001.gif",
        desc: ""
    }, {
        title: "车行道分界线",
        image: "a002.gif",
        desc: ""
    }, {
        title: "车行道分界线",
        image: "a003.gif",
        desc: ""
    }, {
        title: "车行道边缘线",
        image: "a004.gif",
        desc: ""
    }, {
        title: "车行道边缘线",
        image: "a005.gif",
        desc: ""
    }, {
        title: "边缘线的尺寸　单位：cm",
        image: "a006.gif",
        desc: ""
    }, {
        title: "左弯待转区线",
        image: "a007.gif",
        desc: ""
    }, {
        title: "左转弯导向线",
        image: "a008.gif",
        desc: ""
    }, {
        title: "人行横道(正交)",
        image: "a009.gif",
        desc: ""
    }, {
        title: "人行横道(斜交)",
        image: "a010.gif",
        desc: ""
    }, {
        title: "人行横道(信号灯路口)",
        image: "a011.gif",
        desc: ""
    }, {
        title: "人行横道预告标示",
        image: "a012.gif",
        desc: ""
    }, {
        title: "车距确认",
        image: "a013.gif",
        desc: ""
    }, {
        title: "车距确认线尺寸",
        image: "a014.gif",
        desc: ""
    }, {
        title: "直接式出口标线",
        image: "a015.gif",
        desc: ""
    }, {
        title: "平行式出口标线",
        image: "a016.gif",
        desc: ""
    }, {
        title: "直接式入口标线",
        image: "a017.gif",
        desc: ""
    }, {
        title: "平行式入口标线",
        image: "a018.gif",
        desc: ""
    }, {
        title: "平行式停车位",
        image: "a019.gif",
        desc: ""
    }, {
        title: "倾斜式停车位",
        image: "a020.gif",
        desc: ""
    }, {
        title: "垂直式停车位",
        image: "a021.gif",
        desc: ""
    }, {
        title: "出租车专用待客停车位",
        image: "a022.gif",
        desc: ""
    }, {
        title: "出租车专用上下客车位",
        image: "a023.gif",
        desc: ""
    }, {
        title: "港湾式停靠站",
        image: "a024.gif",
        desc: ""
    }, {
        title: "港湾式停靠站",
        image: "a025.gif",
        desc: ""
    }, {
        title: "收费岛地面标线",
        image: "a026.gif",
        desc: ""
    }, {
        title: "行车速度≤40km/h时的导向箭头",
        image: "a027.gif",
        desc: ""
    }, {
        title: "行车速度在60-80km/h时的导向箭头",
        image: "a028.gif",
        desc: ""
    }, {
        title: "最高速度",
        image: "a029.gif",
        desc: ""
    }, {
        title: "大型车",
        image: "a030.gif",
        desc: ""
    }, {
        title: "小型车",
        image: "a031.gif",
        desc: ""
    }, {
        title: "超车道",
        image: "a032.gif",
        desc: ""
    }, {
        title: "非机动车车道标记",
        image: "a033.gif",
        desc: ""
    } ]
}, {
    title: "道路施工安全设施设置示例",
    list: [ {
        title: "双车道路面局部施工",
        image: "b001.jpg",
        desc: "双车道路面局部施工时设施布设例"
    }, {
        title: "视距不良双车道路面局部施工",
        image: "b002.jpg",
        desc: "视距不良双车道路面局部施工时设施布设例"
    }, {
        title: "改道施工",
        image: "b003.jpg",
        desc: "改道施工时设施布设例"
    }, {
        title: "四车道以上道路一侧路面施工",
        image: "b004.jpg",
        desc: "四车道以上道路一侧路面施工时设施布设例"
    }, {
        title: "同向车道中有一条车道路面施工",
        image: "b005.jpg",
        desc: "同向车道中有一条车道路面施工时设施布设例"
    }, {
        title: "同向车道中有两条车道以上路面施工",
        image: "b006.jpg",
        desc: "同向车道中有两条车道以上路面施工时设施布设例"
    }, {
        title: "高速公路一侧施工",
        image: "b007.jpg",
        desc: "高速公路一侧施工，利用中央分隔带紧急开口绕行时的设施布设例"
    }, {
        title: "市区道路交叉口有一侧路面施工",
        image: "b008.jpg",
        desc: "市区道路交叉口，有一侧路面施工时的设施布设例"
    }, {
        title: "市区道路交叉口中心线附近施工",
        image: "b009.jpg",
        desc: "市区道路交叉口中心线附近施工时的设施布设例"
    }, {
        title: "市区道路交叉口中心线附近施工",
        image: "b010.jpg",
        desc: "市区道路交叉口中心线附近施工时的设施布设例"
    }, {
        title: "市区道路两侧施工只能单向行驶",
        image: "b011.jpg",
        desc: "市区道路两侧施工只能单向行驶时的设施布设例"
    }, {
        title: "高速公路出口三角地带附近施工",
        image: "b012.jpg",
        desc: "高速公路出口三角地带附近施工时的设施布设例"
    }, {
        title: "高速公路出口减速车道施工",
        image: "b013.jpg",
        desc: "高速公路出口减速车道施工时的设施布设例"
    }, {
        title: "高速公路入口加速车道边缘施工",
        image: "b014.jpg",
        desc: "高速公路入口加速车道边缘施工时的设施布设例"
    }, {
        title: "高速公路入口加速车道施工",
        image: "b015.jpg",
        desc: "高速公路入口加速车道施工时的设施布设例"
    } ]
} ];